package com.example.test400.Domein;

public class Tekstvoorblog {



    //dit is puur omdat er anders in mn startupListener een enorme string staat waardoor het niet meer duidelijk en overzichtelijk is:
    public static String tekstArtikel1 = "Joanna is 25 jaar. Ze komt uit een stabiel gezin, eet goed en beschrijft haar fysieke conditie als uitstekend. Nou ja, op een recente blessure na dan. Tijdens een Jiujitsu-training bezeerde ze haar arm. De zelfverdedigingssport is het belangrijkste in haar leven. Na het winnen van een wedstrijd voelt ze zich high. Ze zit iedere dag zes uur in de sportschool. Als ze een training mist, doet ze later een extra lange sessie om te compenseren.\n" +
            "\n" +
            "Haar blessure hield lang aan, omdat ze te snel weer begon met Jiujitsu. Ze ging in tegen het advies van haar arts om tijdelijk te stoppen. Maar als ze langer dan een dag niet kan sporten, voelt ze zich misselijk. Leren lukt ook alleen na een bezoek aan de sportschool. Haar vriendje verbrak de relatie vanwege haar strenge sportregime. Joanne probeert haar trainingsschema terug te brengen. Zonder succes. Ook al beschrijft ze zichzelf niet als ‘verslaafd’, ze realiseert zich dat ze een probleem heeft.\n" +
            "\n" +
            "Fijn gevoel\n" +
            "Sporten, en dan vooral cardiotraining, vermindert angst en andere negatieve gevoelens zoals stress. Je zelfvertrouwen krijgt een boost, doordat je er beter uit gaat zien. Of omdat je trots bent dat strenge sportregime vol te houden. Fysieke inspanning vermindert dus nare gemoedstoestanden terwijl het tegelijkertijd positieve gevoelens opwekt. Waar komt dat aangename gevoel van een work-out eigenlijk vandaan? Vanuit de neurobiologie zijn er meerdere verklaringen geopperd. De populairste en meest controversiële verklaring voor sportverslaving is die van de endorfines: lichaamseigen pijnstillers (opiaten) die tijdens het sporten worden afgegeven aan het bloed. Een andere hypothese is dat je lichaamstemperatuur omhoog gaat door te sporten. Daardoor zou je je comfortabel en minder angstig voelen.\n" +
            "\n" +
            "\n" +
            "Fysieke inspanning is goed voor de gemoedstoestand.\n" +
            "\n" +
            " Jaren Wilkey/BYU\n" +
            "\n" +
            "Werk laten schieten\n" +
            "Dit geval van iemand die excessief sport werd in 1997 beschreven in het vakblad Addiction Research. Er zijn meer mensen met Joanna’s neigingen, ook in Nederland, blijkt uit een onderzoek van Sabine Janssen. In 2011 onderzocht zij als masterstudent vierduizend sporters van het Nijmeegse Universitair Sportcentrum, met behulp van vragenlijsten. Ze constateerde een verslaving bij anderhalf procent van de sporters, die gemiddeld 7,5 uur per week met hun sport bezig waren om irritatie en stress tegen te gaan. Minderen lukte niet. Overmatig sporten is vooral mentaal funest. ‘Sportverslaafden’ verkiezen hun beweging boven andere verantwoordelijkheden, zag Janssen. Mannen brengen minder tijd door met hun familie en vrouwen laten vooral hun werk ervoor schieten.\n" +
            "\n" +
            "Gezien vanuit de hersenen\n" +
            "Hebben bovengenoemde mensen inderdaad een sportverslaving? Bestaat er überhaupt zoiets als verslaafd raken aan lichaamsbeweging? Onder wetenschappers is het nog voer voor discussie. Sportverslaving wordt in de vijfde editie van de Diagnostic and Statistical Manual of Mental Disorder (DSM), hét handboek voor psychiatrische aandoeningen, (nog) niet erkend als gedragsverslaving. Overigens geldt dat ook voor overmatig shoppen, eten of gamen.\n" +
            "\n" +
            "Hersenonderzoeker Ruth van Holst twijfelt of excessief sporten zich kan opwerken tot ware verslaving. Zij doet aan het AMC en het Donders Instituut in Nijmegen onderzoek naar gokverslaving en bekijkt de kwestie vanuit het hersenperspectief. “Alleen gokken valt nu onder gedragsverslaving in de DSM, omdat het overeenkomsten vertoont met drugsverslaving”, legt Van Holst uit. “Bij zowel drugs- als gokverslaving werkt de prefrontale cortex minder goed, waardoor je moeilijk je gedrag onder controle kan houden. Daarnaast is bij verslaafden het beloningscentrum vooral gericht op de beloning vanuit de verslaving, terwijl het minder gevoelig is voor normale beloningen.” Ze betwijfelt of er ook zoiets gebeurt in het brein van excessieve sporters. Sportverslaving of eetstoornis?\n" +
            "Een belangrijk kenmerk van een verslaving is dat het gedrag een probleem vormt voor jezelf en je omgeving. Met sporten kan dat zo zijn, bewijst Joanna’s geval. Maar, voor je van een sportverslaving kunt spreken, moet je zeker weten dat het gedrag niet komt door een andere stoornis, legt Van Holst uit. Ruim veertig procent van de mensen met een eetstoornis doet aan obsessief sporten. Sporten is hier een symptoom van een eetstoornis.\n" +
            "\n" +
            "In Nederland maakt geen enkele reguliere verslavingszorginstelling melding van cliënten met een sportverslaving, volgens een publicatie uit 2014 van het Instituut voor Onderzoek naar Leefwijzen en Verslaving (IVO). Enkele private instellingen rapporteren wel tientallen meldingen van cliënten, maar alleen in combinatie met eetstoornissen en drugsproblemen. Van Holst denkt dat als een sportverslaving op zichzelf bestaat, dat zeldzaam is. En dus moeilijk te onderzoeken. “In de literatuur zijn enkele gevallen beschreven, maar dat is te weinig om een te diagnose ontwikkelen”, zegt de hersenwetenschapper. “En als er geen officiële diagnose bestaat, zijn er ook geen officiële cijfers over hoe vaak het voorkomt.” De grens tussen gezond en ongezond\n" +
            "Klinisch psycholoog en specialist in gedragsverslaving Marilyn Freimuth van de Fielding Graduate University in Californië (Verenigde Staten), is er heilig van overtuigd dat sportverslaving bestaat. In 2011 schreef ze met collega’s een wetenschappelijk artikel om het fenomeen op te helderen. Zwart-wit is het allerminst. Wat onderscheidt de fanatiekeling die dagelijks naar de sportschool gaat van iemand die niet kan stoppen met lichaamsbeweging?\n" +
            "\n" +
            "Een atleet die meerdere keren per dag traint voor de Olympische Spelen is niet per se verslaafd aan zijn sport. Hoe zit het met een hardloper die na het missen van een training vijf kilometer extra toevoegt aan het loopschema? Voor het vaststellen van alcohol- en drugsverslaving zijn er bepaalde criteria die, in iets aangepaste vorm, ook opgaan voor sportverslaving, vinden onderzoekers als Freimuth. Op basis van die kenmerken ontwikkelden psychologen vragenlijsten om verslaafden eruit te pikken (zie kader).\n" +
            "\n" +
            "“Sommige mensen sporten zoveel, dat het nadelig voor ze uitpakt”, licht Freimuth toe. De negatieve effecten kunnen lichamelijk zijn, zoals door chronische blessures, en interpersoonlijk, bijvoorbeeld door ruzie met een partner over de tijd die de sportschool in beslag neemt. Ondanks de problemen die hun sportgedrag oplevert, vinden sommigen het moeilijk om te stoppen of te minderen. “Die twee uitkomsten, negatieve gevolgen voor het dagelijks leven en moeite om te stoppen, zijn belangrijke kenmerken van verslaving”, aldus Freimuth.\n" +
            "\n" +
            "Dubbel doel\n" +
            "Bij dwangmatige handelingen, zoals schoonmaken, zie je die uitkomsten ook. Maar er is een verschil. Freimuth: “Dwanghandelingen worden voornamelijk uitgevoerd om angst te verminderen. Verslavingen dienen een dubbel doel: het gedrag is een manier om te ontsnappen aan negatieve gevoelens als angst, maar tegelijkertijd moet het ook krachtige genotservaringen creëren. Niet veel onderzoekers maken dit onderscheid. In mijn opvatting hebben sommige mensen die excessief sporten een ‘sportdwang’, terwijl anderen een verslaving hebben.” Studies naar sportverslaving stuiten op een iets hoger percentage slachtoffers dan masterstudent Janssen aantrof: twee tot drie procent van de sportende mensen kampt met exercise addiction. Wie wil ontsnappen aan onplezierige gevoelens loopt een grotere kans in de penarie te raken. Wie beweegt om zelfvertrouwen op te bouwen, loopt eveneens risico. Ook opmerkelijk: ultramarathonlopers en studenten bewegingswetenschappen lijken daarnaast extra gevoelig voor verslaving. Freimuth: “Steeds vaker gaan sporten of steeds langer dan voordien gepland, oftewel de controle verliezen, is een teken dat iemand afstevent op een verslaving.”\n" +
            "\n" +
            "De onenigheid over lichaamsbeweging als verslaving of als andere stoornis past binnen een bredere discussie. En die gaat over definities. “Vanuit de wetenschap is er veel discussie over wanneer we ophouden met problematisch gedrag een verslaving te noemen”, zegt Van Holst. Gamen, teveel eten, seks, sociale media: elk gedrag kan de spuigaten uitlopen. Om verslaving zuiver te houden moeten we oppassen met dingen als zodanig te benoemen, is zij van mening. Freimuth daarentegen, vindt dat bepaalde patronen in lichaamsbeweging zich nou eenmaal het best laten omschrijven als verslaving. Of overmatig sporten het label ‘verslaving’ verdient of niet, feit blijft dat excessieve sporters hulp nodig hebben. Daar zijn de twee wetenschappers het volledig over eens.";


    public static String tekstVoorArtikel2 = "“Wat we vonden was niet naar verwachting”, zegt Eelco van Dongen. “Uit dieronderzoek was namelijk gebleken dat sporten direct na een geheugentaak het geheugen verbetert.” Dat het bij mensen pas werkt na een paar uur uitstel, was daarom een van die toevallige ontdekkingen waar het in de wetenschap van wemelt.\n" +
            "\n" +
            "Hersenonderzoeker Van Dongen en vier collega’s deden dit onderzoek aan het Donders Instituut van de Nijmeegse Radboud Universiteit. Ze verdeelden 72 proefpersonen in drie groepen: een groep die meteen na de geheugentaak sportte, een groep die pas vier uur later op de fietsergometer klom, en een groep die niet sportte tot aan de herhalingstest, twee dagen later. Van Dongen en zijn collega’s verwachtten dat de eerste groep het sterkste effect zou vertonen, terwijl de laat- en niet-fietsers eigenlijk bedoeld waren als controlegroepen.\n" +
            "\n" +
            "\n" +
            "Van de drie groepen proefpersonen moest de ene groep direct na de geheugentaak sporten, de tweede groep pas vier uur na de geheugentaak, en de derde groep helemaal niet tot aan de herhalingstest, twee dagen later. Het trainen bestond uit een stevige ergometertraining van 35 minuten.\n" +
            " public domain\n" +
            "Plaatjes onthouden\n" +
            "Bij de geheugentaak moest elke proefpersoon negentig plaatjes van een voorwerp bekijken, en onthouden op welk plaats het stond. Meteen na deze sessie was er een test met de voorwerpen in het midden van het plaatje, om te zien van hoeveel voorwerpen de positie op het plaatje correct onthouden was. Twee dagen later kwamen de proefpersonen terug en deden dezelfde test nogmaals. Bij deze herhalingstest lagen de proefpersonen in een fMRI-scanner, zodat hun hersenactiviteit in kaart kon worden gebracht.\n" +
            "\n" +
            "Het resultaat was verrassend: de groep die meteen na de eerste geheugentaak had gesport, scoorde niet beter dan de groep die niet sportte. Maar de groep die vier uur na de geheugentaak sportte, scoorde duidelijk beter. In alle groepen herinnerden de proefpersonen zich bij de herhalingstest minder plaatjes dan bij de eerste test, maar bij de ‘laat-sporten’-groep beklijfde de kennis het best; die personen hielden bij de herhalingstest 87 procent van hun directe herinnering over, tegen de beide andere groepen 80 procent.\n" +
            "\n" +
            "Sporten direct na de geheugentaak werkt dus niet eens minder goed dan uitgesteld sporten, het werkt helemaal niet. Signaalstoffen in de hersenen\n" +
            "Waarom sporten überhaupt helpt om herinneringen te behouden is maar zeer ten dele bekend. De theorie is dat de hersenen herinneringen eerst voor korte tijd opslaan, en daarna een selectie daaruit voor langere tijd. Bij proefdieren is gemeten dat die langetermijnopslag (‘consolidatie’) gepaard gaat met een verhoogde productie van bepaalde signaalstoffen in de hersenen, zoals dopamine en noradrenaline. Maar ook intensieve lichamelijke inspanning stimuleert de productie van deze stoffen.\n" +
            "\n" +
            "Waarom bij mensen stimuleren van deze consolidatie door sporten pas na uren effect heeft is niet bekend. Van Dongen: “Mensen herinneren zich heel andere dingen dan knaagdieren, en op een andere manier. Dus zo vreemd is dat nu ook weer niet.” Volgens Van Dongen is een mogelijke verklaring dat de productie van dopamine en noradrenaline kort na de geheugentaak toch al optimaal is voor consolidatie, na een paar uur inzakt, en dan kan worden opgekrikt door sporten. Meer dan speculatie is dit vooralsnog niet. Hippocampus\n" +
            "Uit de hersenscans tijdens de herhalingstest bleek (gemiddeld) een duidelijk verschil tussen iemand die een correct en iemand die een incorrect antwoord geeft. Dit verschil was echter voor alle drie de groepen hetzelfde. Wat de scans van de ‘laat-sporten’-groep onderscheidde van de rest, was de activiteit in de hippocampus, een gedeelte van de hersenen dat nauw betrokken is bij de vorming van herinneringen. Bij de ‘laat-sporten’-groep bleken de patronen die oplichtten in dit gebied minder ruis te vertonen dan bij de twee andere groepen.\n" +
            "\n" +
            "Rest de vraag, of het min of meer willekeurig gekozen uitstel van vier uur optimaal is. Van Dongen, die inmiddels op een ander onderzoeksterrein werkt: “Dit is onderzoek dat relatief veel mankracht en tijd vergt, maar er zijn plannen om dit nog verder uit te gaan zoeken.” Als je een scholier bent die rond deze tijd toch moet studeren voor een herexamen, hoef je daar niet op te wachten. Neem gewoon de proef op de som: ga ongeveer vier uur nadat je de boeken aan de kant gegooid hebt sporten of een flink stuk fietsen. Kwaad kan het zeker niet. ";


}
